import postgres from 'npm:postgres@3.4.3'
const url=Deno.env.get('SUPABASE_DB_URL');if(!url)throw new Error('missing_db_url')
const db=postgres(url,{max:1,prepare:false,idle_timeout:20,connect_timeout:10}),enc=new TextEncoder(),dec=new TextDecoder()
const MAX_REQUEST_BYTES=256_000,MAX_TEXT_CHARS=5_000
function b64d(s:string){const p='='.repeat((4-s.length%4)%4),b=atob(s.replace(/-/g,'+').replace(/_/g,'/')+p);return Uint8Array.from(b,c=>c.charCodeAt(0))}
async function auth(req:Request){const h=req.headers.get('authorization')||'';if(!h.startsWith('Bearer '))return false;const p=h.slice(7).split('.');if(p.length!==3||p[0]!=='v1')return false;try{const r=await db`select value from sintergia.server_secrets where name='session_hmac'`;if(!r.length)return false;const k=await crypto.subtle.importKey('raw',enc.encode(String(r[0].value)),{name:'HMAC',hash:'SHA-256'},false,['verify']);if(!await crypto.subtle.verify('HMAC',k,b64d(p[2]),enc.encode(p[1])))return false;const x=JSON.parse(dec.decode(b64d(p[1])));return Number(x?.exp)>Date.now()/1000}catch{return false}}
function cors(req:Request):Record<string,string>{const o=req.headers.get('origin'),a=(Deno.env.get('ALLOWED_ORIGINS')||'').split(',').map(x=>x.trim()).filter(Boolean),h:Record<string,string>={'Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'authorization,content-type,x-requested-with,x-sintergia-request-id','Access-Control-Max-Age':'86400','Vary':'Origin'};if(o&&a.includes(o)){h['Access-Control-Allow-Origin']=o;h['Access-Control-Allow-Credentials']='true'}return h}
function out(req:Request,s:number,b:unknown){return new Response(JSON.stringify(b),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...cors(req)}})}
async function readJsonLimited(req:Request){if(Number(req.headers.get('content-length')||0)>MAX_REQUEST_BYTES)throw new RangeError('large');if(!req.body)throw new SyntaxError('empty');const rd=req.body.getReader(),chunks:Uint8Array[]=[];let n=0;try{for(;;){const {done,value}=await rd.read();if(done)break;n+=value.byteLength;if(n>MAX_REQUEST_BYTES){await rd.cancel().catch(()=>undefined);throw new RangeError('large')}chunks.push(value)}}finally{rd.releaseLock()}const all=new Uint8Array(n);let p=0;for(const c of chunks){all.set(c,p);p+=c.length}const v:unknown=JSON.parse(dec.decode(all));if(!v||typeof v!=='object'||Array.isArray(v))throw new SyntaxError('invalid');return v as Record<string,unknown>}
function e164(value:string){const v=value.replace(/[^+\d]/g,'');return /^\+\d{8,15}$/.test(v)?v:null}
async function twilio(to:string,body:string){const sid=Deno.env.get('TWILIO_ACCOUNT_SID')||'',token=Deno.env.get('TWILIO_AUTH_TOKEN')||'',sender=Deno.env.get('TWILIO_WHATSAPP_FROM')||'';if(!sid||!token||!sender)return {ok:false,error:'whatsapp_provider_not_configured'};const from=sender.startsWith('whatsapp:')?sender:'whatsapp:'+sender,params=new URLSearchParams({From:from,To:'whatsapp:'+to,Body:body});const response=await fetch('https://api.twilio.com/2010-04-01/Accounts/'+encodeURIComponent(sid)+'/Messages.json',{method:'POST',headers:{Authorization:'Basic '+btoa(sid+':'+token),'Content-Type':'application/x-www-form-urlencoded'},body:params,signal:AbortSignal.timeout(15_000)});const data=await response.json().catch(()=>({}));if(!response.ok){console.error('cita_whatsapp_provider_error',response.status);return {ok:false,error:'whatsapp_provider_error'}}return {ok:true,provider:'twilio',provider_message_id:data?.sid||null,status:data?.status||'queued'}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return out(req,405,{ok:false,error:'method_not_allowed'});if(!await auth(req))return out(req,401,{ok:false,error:'unauthorized'});let b:Record<string,unknown>;try{b=await readJsonLimited(req)}catch(e){return out(req,e instanceof RangeError?413:400,{ok:false,error:e instanceof RangeError?'request_too_large':'invalid_json'})}const to=e164(String(b.to||b.telefono||'')),texto=String(b.texto||b.body||b.message||'').trim(),avisoId=String(b.avisoId||b.aviso_id||'').trim().slice(0,200),cliente=String(b.cliente||'').trim().slice(0,300),provider=String(Deno.env.get('WHATSAPP_PROVIDER')||'twilio').toLowerCase(),requestId=String(req.headers.get('x-sintergia-request-id')||crypto.randomUUID()).replace(/[^A-Za-z0-9._:-]/g,'_').slice(0,200);if(!to||!texto||texto.length>MAX_TEXT_CHARS||!avisoId)return out(req,400,{ok:false,error:'invalid_request'});if(provider!=='twilio')return out(req,503,{ok:false,error:'whatsapp_provider_unsupported'});let token=String(b.token||'').trim();try{const existing=token?await db`select token,destination from sintergia.cita_messages where token=${token} limit 1`:[];if(existing.length&&String(existing[0].destination)!==to)return out(req,409,{ok:false,error:'token_destination_mismatch'});if(!existing.length)token=crypto.randomUUID()+crypto.randomUUID().replaceAll('-','');const base=(Deno.env.get('PUBLIC_FUNCTIONS_BASE_URL')||'https://bgjicsowspppsjzigazb.supabase.co/functions/v1').replace(/\/$/,'');const yes=base+'/cita-respuesta?token='+encodeURIComponent(token)+'&respuesta=si',no=base+'/cita-respuesta?token='+encodeURIComponent(token)+'&respuesta=no';const result=await twilio(to,texto+'\n\nConfirmar cita: '+yes+'\nNecesito otra fecha: '+no);if(!result.ok)return out(req,503,{...result,token});const payload={avisoId,cliente,provider:result.provider,provider_message_id:result.provider_message_id,request_id:requestId,created_at:new Date().toISOString()};if(existing.length)await db`update sintergia.cita_messages set aviso_id=${avisoId},destination=${to},payload=${JSON.stringify(payload)}::jsonb,updated_at=now() where token=${token}`;else await db`insert into sintergia.cita_messages(token,aviso_id,channel,destination,payload) values(${token},${avisoId},'whatsapp',${to},${JSON.stringify(payload)}::jsonb)`;return out(req,200,{ok:true,messageId:result.provider_message_id||null,token,provider:result.provider,request_id:requestId})}catch(e){console.error('cita_whatsapp_error',String(e));return out(req,503,{ok:false,error:'service_unavailable',token:token||null})}})
