import postgres from 'npm:postgres@3.4.3'
const url=Deno.env.get('SUPABASE_DB_URL'); if(!url) throw new Error('missing_db_url')
const db=postgres(url,{max:1,prepare:false,idle_timeout:20,connect_timeout:10})
const enc=new TextEncoder(),dec=new TextDecoder(),MAX_REQUEST_BYTES=256_000,MAX_TEXT_CHARS=10_000
function b64d(s:string){const p='='.repeat((4-s.length%4)%4),b=atob(s.replace(/-/g,'+').replace(/_/g,'/')+p);return Uint8Array.from(b,c=>c.charCodeAt(0))}
async function auth(req:Request){const h=req.headers.get('authorization')||'';if(!h.startsWith('Bearer '))return false;const p=h.slice(7).split('.');if(p.length!==3||p[0]!=='v1')return false;try{const r=await db`select value from sintergia.server_secrets where name='session_hmac'`;if(!r.length)return false;const k=await crypto.subtle.importKey('raw',enc.encode(String(r[0].value)),{name:'HMAC',hash:'SHA-256'},false,['verify']);if(!await crypto.subtle.verify('HMAC',k,b64d(p[2]),enc.encode(p[1])))return false;const x=JSON.parse(dec.decode(b64d(p[1])));return Number(x?.exp)>Date.now()/1000}catch{return false}}
function cors(req:Request):Record<string,string>{const o=req.headers.get('origin'),a=(Deno.env.get('ALLOWED_ORIGINS')||'').split(',').map(x=>x.trim()).filter(Boolean),h:Record<string,string>={'Access-Control-Allow-Methods':'POST,OPTIONS','Access-Control-Allow-Headers':'authorization,content-type,x-sintergia-request-id','Access-Control-Max-Age':'86400','Vary':'Origin'};if(o&&a.includes(o)){h['Access-Control-Allow-Origin']=o;h['Access-Control-Allow-Credentials']='true'}return h}
function out(req:Request,s:number,b:unknown){return new Response(JSON.stringify(b),{status:s,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...cors(req)}})}
async function readJsonLimited(req:Request){if(Number(req.headers.get('content-length')||0)>MAX_REQUEST_BYTES)throw new RangeError('large');if(!req.body)throw new SyntaxError('empty');const rd=req.body.getReader(),chunks:Uint8Array[]=[];let n=0;try{for(;;){const {done,value}=await rd.read();if(done)break;n+=value.byteLength;if(n>MAX_REQUEST_BYTES){await rd.cancel().catch(()=>undefined);throw new RangeError('large')}chunks.push(value)}}finally{rd.releaseLock()}const all=new Uint8Array(n);let p=0;for(const c of chunks){all.set(c,p);p+=c.length}const v:unknown=JSON.parse(dec.decode(all));if(!v||typeof v!=='object'||Array.isArray(v))throw new SyntaxError('invalid');return v as Record<string,unknown>}
function phone(v:string){const x=v.replace(/[^+\d]/g,'');return /^\+\d{8,15}$/.test(x)?x:null}
function email(v:string){return v.length<=254&&!/[;,]/.test(v)&&/^[^\s<>@]+@[^\s<>@]+\.[^\s<>@]+$/.test(v)}
function escapeHtmlText(v:string){return v.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;').replace(/\r\n?|\n/g,'<br>')}
async function sendWa(to:string,body:string){const sid=Deno.env.get('TWILIO_ACCOUNT_SID')||'',secret=Deno.env.get('TWILIO_AUTH_TOKEN')||'',from=Deno.env.get('TWILIO_WHATSAPP_FROM')||'';if(!sid||!secret||!from)return {ok:false,error:'whatsapp_provider_not_configured'};const f=from.startsWith('whatsapp:')?from:'whatsapp:'+from,p=new URLSearchParams({From:f,To:'whatsapp:'+to,Body:body});const r=await fetch('https://api.twilio.com/2010-04-01/Accounts/'+encodeURIComponent(sid)+'/Messages.json',{method:'POST',headers:{Authorization:'Basic '+btoa(sid+':'+secret),'Content-Type':'application/x-www-form-urlencoded'},body:p,signal:AbortSignal.timeout(15_000)});const j=await r.json().catch(()=>({}));if(!r.ok)return {ok:false,error:'whatsapp_provider_error'};return {ok:true,provider:'twilio',provider_message_id:j?.sid||null,status:j?.status||'queued'}}
async function sendMail(to:string,body:string,rid:string){const key=Deno.env.get('RESEND_API_KEY')||'',from=Deno.env.get('EMAIL_FROM')||'';if(!key||!from)return {ok:false,error:'email_provider_not_configured'};const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json','Idempotency-Key':rid},body:JSON.stringify({from,to:[to],subject:'Recordatorio de cita — SintergiaSE',html:escapeHtmlText(body)}),signal:AbortSignal.timeout(15_000)});const j=await r.json().catch(()=>({}));if(!r.ok)return {ok:false,error:'email_provider_error'};return {ok:true,provider:'resend',provider_message_id:j?.id||null}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return out(req,405,{ok:false,error:'method_not_allowed'});if(!await auth(req))return out(req,401,{ok:false,error:'unauthorized'});let b:Record<string,unknown>;try{b=await readJsonLimited(req)}catch(e){return out(req,e instanceof RangeError?413:400,{ok:false,error:e instanceof RangeError?'request_too_large':'invalid_json'})}const t=String(b.token||'').trim(),canal=String(b.canal||'').toLowerCase(),to=String(b.to||'').trim(),texto=String(b.texto||b.body||b.message||'').trim(),rid=String(req.headers.get('x-sintergia-request-id')||crypto.randomUUID()).replace(/[^A-Za-z0-9._:-]/g,'_').slice(0,200);if(!t||!to||!texto||texto.length>MAX_TEXT_CHARS||!['email','whatsapp'].includes(canal))return out(req,400,{ok:false,error:'invalid_request'});if(canal==='email'&&!email(to))return out(req,400,{ok:false,error:'invalid_email'});if(canal==='whatsapp'&&!phone(to))return out(req,400,{ok:false,error:'invalid_phone'});try{const rows=await db`select token from sintergia.cita_messages where token=${t} limit 1`;if(!rows.length)return out(req,404,{ok:false,error:'unknown_token'});const result=canal==='whatsapp'?await sendWa(phone(to)!,texto):await sendMail(to,texto,rid);if(!result.ok)return out(req,503,result);await db`update sintergia.cita_messages set payload=payload || ${JSON.stringify({lastReminder:{channel:canal,request_id:rid,provider:result.provider,provider_message_id:result.provider_message_id,sent_at:new Date().toISOString()}})}::jsonb,updated_at=now() where token=${t}`;return out(req,200,{ok:true,...result,request_id:rid})}catch(e){console.error('cita_recordatorio_error',String(e));return out(req,503,{ok:false,error:'service_unavailable'})}})
